name = "gdo"
version = "0.1.0"
description = "A database access library for Gleam with a typed, functional API."
licences = ["Apache-2.0"]
repository = { type = "github", user = "hebertcisco", repo = "gdo" }
links = [
  { title = "Repository", href = "https://github.com/hebertcisco/gdo" }
]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
sqlight = ">= 1.1.0 and < 2.0.0"
parrot = ">= 2.2.1 and < 3.0.0"
mysql = ">= 1.9.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
