name = "gdo"
version = "0.1.0"
description = "A Gleam database access library inspired by PDO, starting with SQLite and a cross-target architecture."
licences = ["Apache-2.0"]
repository = { type = "github", user = "hebertcisco", repo = "gdo" }
links = [
  { title = "Repository", href = "https://github.com/hebertcisco/gdo" }
]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
